source :rubygems
gem 'eventmachine'
gem 'thin'
gem 'hiredis', '~> 0.3.1'
gem 'redis', '>= 2.2.0', :require => ['redis', 'redis/connection/hiredis']
gem 'sinatra'
gem 'async_sinatra'
gem 'sinatra-settings'
gem 'rack', :git => 'git://github.com/rack/rack.git'
gem 'rack-contrib', :git => 'git://github.com/rack/rack-contrib.git'
gem 'activesupport'
gem 'actionpack'
gem 'haml'
gem 'sass'
gem 'json'
gem 'rake'
gem 'SystemTimer', :platforms => :ruby_18
gem 'rack-flash'
gem 'net-dns'
gem 'sinatra-static-assets', :require => 'sinatra/static_assets'
gem 'rack-flash3', :require => 'rack/flash'
